# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fd8f4da404ded669822b5a82bc4b22cbf2dddbdbba4d9ce662ea2d90b8fa81d44a3abe94012851e17f3a3f801b837950b695b8658330c1771b4d0071b0af892

test:
  secret_key_base: c53bb65063fdda227076301fd431a66447f029111f3162c27b73df6d0bd4e17cd2443bd101ce56504ad1ad9b82ab6d84132bdc645f0985abbc69c5da3704043b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
